services:

  gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    environment:
      REDIS_URL: redis://redis:6379
      USER_SERVICE_URL_1: http://user-service-1:3001
      USER_SERVICE_URL_2: http://user-service-2:3001
      USER_SERVICE_URL_3: http://user-service-3:3001

      PRODUCT_SERVICE_URL: http://product-service:3004
      ORDER_SERVICE_URL: http://order-service:3005
      NOTIFICATION_SERVICE_URL: http://notification-service:3006
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: api_gateway
      MONGODB_URL: mongodb://mongodb:27017
    depends_on:
      - redis
      - user-service-1
      - user-service-2
      - user-service-3
      - product-service
      - order-service
      - notification-service
      - mongodb
      - postgres

  redis:
    image: redis:7-alpine
    container_name: api-gateway-redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    container_name: api-gateway-postgres
    environment:
      POSTGRES_USER: gateway
      POSTGRES_PASSWORD: gateway_password
      POSTGRES_DB: api_gateway
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  user-service-1:
    build: ./services/user-service
    container_name: user-service-1
    ports:
      - "3001:3001"

  user-service-2:
    build: ./services/user-service
    container_name: user-service-2
    ports:
      - "3002:3001"

  user-service-3:
    build: ./services/user-service
    container_name: user-service-3
    ports:
      - "3003:3001"

  order-service:
    build: ./services/order-service
    container_name: order-service
    ports:
      - "3005:3005"

  notification-service:
    build: ./services/notification-service
    container_name: notification-service
    ports:
      - "3006:3006"

  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "3004:3004"

  prometheus:
    image: prom/prometheus
    container_name: api-gateway-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./gateway/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    depends_on:
      - gateway

  grafana:
    image: grafana/grafana
    container_name: api-gateway-grafana
    ports:
      - "3007:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: api-gateway-cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: api-gateway-redis-exporter
    ports:
      - "9121:9121"
    environment:
      REDIS_ADDR: redis://redis:6379
    depends_on:
      - redis

  mongodb:
    image: mongo:7
    container_name: api-gateway-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db


volumes:
  prometheus-data:
  grafana-data:
  postgres-data:
  mongodb-data: